### ISSUE TITLE
errno

### ISSUE THREAD

**Issue by denisdemaisbr** [philanc/l5#1]
hi
you must reset errno before call an syscall.

i.e.,
#include <errno.h>

int fn(...) {

errno = 0;
const int fd = open( "/dev/tty0", O_RDWR  );
const int err = errno; // i like that

if ( fd < 0 ) {
...
}

return x;
}

**Comment by philanc** [comment]
Hi Denis,

The libc functions I call do return a value that is either a valid result or a value that indicates an error.  The contract of these functions is usually that _in case of error, they set errno_.  So I must ensure that the return value is tested and that errno is returned _only_ when the return value indicates an error.

In your example:
```
int fd = open( "/dev/tty0", O_RDWR );
if (fd == -1) {
   // here we know that errno has been set by open()
   return errno
}
```
As long as errno is used only as indicated, it is either correctly defined or not used. There is no need to set it to zero before calling the libc function.

If I don't use it somewhere as shown above (ie. within a test of the returned value) it is a bug. Please let me know where you noticed it.  Thanks

Phil

**Comment by denisdemaisbr** [comment]
Hi. the example above* is ilustraded (from my mind).

to see more details about errno at https://wiki.sei.cmu.edu/confluence/pages/viewpage.action?pageId=87152351

**Comment by denisdemaisbr** [comment]
this a simple suggestion. clear errno before a syscall then modify errno

**Comment by philanc** [comment]
> to see more details about errno at https://wiki.sei.cmu.edu/confluence/pages/viewpage.action?pageId=87152351

Thanks for the informative link. I will check and ensure that return indicators _are_ tested, and that errno is set to 0 before calling functions that could return an in-band error indicator.
